### ISSUE TITLE
Error panic runtime error when executing Authz Msg Delegate

### ISSUE THREAD

**Issue by arifintahu** [UptickNetwork/uptick#18]
I got a panic error when trying to execute Msg Authz Exec with Msg Delegate. I am a little bit confused because there's not enough information what was happened.
```
$ uptickd tx authz exec tx-delegate.json --from operator --fees 3000000000000000auptick -y
code: 111222
codespace: undefined
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'runtime error: invalid memory address or nil pointer dereference: panic'
timestamp: ""
tx: null
txhash: 1F0F3946B88EA7C43EA4F4C6CBD64CB6DAA6A094604089D2CA64B87C15A8D182
```

example tx-delegate.json
```json
{
  "body": {
    "messages": [
      {
        "@type": "/cosmos.staking.v1beta1.MsgDelegate",
        "delegator_address": "uptick1yxxx",
        "validator_address": "uptick1xxx",
        "amount": {
          "denom": "auptick",
          "amount": "15910809859993438000"
        }
      }
    ],
    "memo": "",
    "timeout_height": "0",
    "extension_options": [],
    "non_critical_extension_options": []
  },
  "auth_info": {
    "signer_infos": [],
    "fee": {
      "amount": [
        {
          "denom": "auptick",
          "amount": "3000000000000000"
        }
      ],
      "gas_limit": "200000",
      "payer": "",
      "granter": ""
    },
    "tip": null
  },
  "signatures": []
}
```

**Comment by arifintahu** [comment]
Reproduce command using Authz exec MsgSend
```bash
uptickd keys add mykey
uptickd keys add test
uptickd tx authz grant $(uptickd keys show test -a) send --spend-limit 1000000000000auptick --from mykey -y
uptickd q authz grants-by-grantee $(uptickd keys show test -a)

uptickd keys add recipient
uptickd tx bank send mykey $(uptickd keys show recipient -a) 1000auptick --from test --generate-only | jq > tx-send.json
uptickd tx authz exec tx-send.json --from test -y
```

Response
```bash
code: 111222
codespace: undefined
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'runtime error: invalid memory address or nil pointer dereference: panic'
timestamp: ""
tx: null
txhash: 8CB6A797DE3CCE021983618022A4F243F139742094F1FCD43D4A35F489AA84ED
```

Log
```bash
12:18PM ERR ante handler panicked error="runtime error: invalid memory address or nil pointer dereference" stack trace="goroutine 9372 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/evmos/ethermint/app/ante.Recover({0x3412218, 0xc001204cc0}, 0xc0047426d0)\n\tgithub.com/evmos/ethermint@v0.20.0/app/ante/ante.go:85 +0xff\npanic({0x241ef20, 0x473ba00})\n\truntime/panic.go:838 +0x207\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/x/auth/ante/setup.go:57 +0x1e6\npanic({0x241ef20, 0x473ba00})\n\truntime/panic.go:838 +0x207\ngithub.com/UptickNetwork/uptick/app/ante.ValidatorCommissionDecorator.validateAuthz({{_, _}}, {{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, ...}, ...}, ...)\n\tgithub.com/UptickNetwork/uptick/app/ante/comission.go:52 +0xce\ngithub.com/UptickNetwork/uptick/app/ante.ValidatorCommissionDecorator.AnteHandle({{_, _}}, {{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, ...}, ...}, ...)\n\tgithub.com/UptickNetwork/uptick/app/ante/comission.go:34 +0x22b\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.AnteHandle({{_, _}, {_, _}, {_, _}, _}, {{0x3410c38, 0xc000052090}, {0x3421d60, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/x/auth/ante/fee.go:67 +0x337\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ConsumeTxSizeGasDecorator.AnteHandle({{_, _}}, {{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/x/auth/ante/basic.go:142 +0x34f\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ValidateMemoDecorator.AnteHandle({{_, _}}, {{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/x/auth/ante/basic.go:66 +0x2d7\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.TxTimeoutHeightDecorator.AnteHandle({}, {{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/x/auth/ante/basic.go:205 +0x297\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/types/handler.go:40 +0x136\ngithub.com/evmos/ethermint/app/ante.MinGasPriceDecorator.AnteHandle({{_, _}, {_, _}}, {{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, ...}, ...}, ...)\n\tgithub.com/evmos/ethermint@v0.20.0/app/ante/fees.go:74 +0x392\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ValidateBasicDecorator.AnteHandle({}, {{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/x/auth/ante/basic.go:34 +0x157\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle({}, {{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/x/auth/ante/setup.go:62 +0x593\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/types/handler.go:40 +0x136\ngithub.com/evmos/ethermint/app/ante.RejectMessagesDecorator.AnteHandle({}, {{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, ...}, ...}, ...)\n\tgithub.com/evmos/ethermint@v0.20.0/app/ante/reject_msgs.go:25 +0xf7\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/types/handler.go:40 +0x136\ngithub.com/UptickNetwork/uptick/app/ante.NewAnteHandler.func1({{0x3410c38, 0xc000052090}, {0x3421d60, 0xc005b7c940}, {{0xb, 0x0}, {0xc004f8d710, 0xd}, 0xf2, {0x2b8e696a, ...}, ...}, ...}, ...)\n\tgithub.com/UptickNetwork/uptick/app/ante/ante.go:52 +0x5fc\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0015fa1c0, 0x0, {0xc00022e340, 0x18d, 0x18f})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/baseapp/baseapp.go:694 +0x716\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).CheckTx(0xc0015fa1c0, {{0xc00022e340?, 0xc00148b080?, 0xc00148b188?}, 0x46b8860?})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.13/baseapp/abci.go:244 +0x86\ngithub.com/tendermint/tendermint/abci/client.(*localClient).CheckTxAsync(0xc00125a360, {{0xc00022e340?, 0xd67840?, 0xc00104b900?}, 0x46b8978?})\n\tgithub.com/tendermint/tendermint@v0.34.28/abci/client/local_client.go:104 +0x118\ngithub.com/tendermint/tendermint/proxy.(*appConnMempool).CheckTxAsync(0xc00104b900?, {{0xc00022e340?, 0x0?, 0x198?}, 0x46b89f8?})\n\tgithub.com/tendermint/tendermint@v0.34.28/proxy/app_conn.go:126 +0x26\ngithub.com/tendermint/tendermint/mempool/v0.(*CListMempool).CheckTx(0xc00123eb60, {0xc00022e340, 0x18d, 0x18f}, 0x0?, {0x20?, {0x0?, 0x50003?}})\n\tgithub.com/tendermint/tendermint@v0.34.28/mempool/v0/clist_mempool.go:254 +0x32d\ngithub.com/tendermint/tendermint/rpc/core.BroadcastTxSync(0xc001279180, {0xc00022e340, 0x18d, 0x18f})\n\tgithub.com/tendermint/tendermint@v0.34.28/rpc/core/mempool.go:36 +0xf6\nreflect.Value.call({0x23da3e0?, 0x2ff0b08?, 0x30?}, {0x276fda5, 0x4}, {0xc005b51110, 0x2, 0x18?})\n\treflect/value.go:556 +0x845\nreflect.Value.Call({0x23da3e0?, 0x2ff0b08?, 0x21d?}, {0xc005b51110, 0x2, 0x2})\n\treflect/value.go:339 +0xbf\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1({0x340e920, 0xc0056041c8}, 0xc003543400)\n\tgithub.com/tendermint/tendermint@v0.34.28/rpc/jsonrpc/server/http_json_handler.go:108 +0x11f9\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1({0x340e920?, 0xc0056041c8?}, 0x7f8ec93eba68?)\n\tgithub.com/tendermint/tendermint@v0.34.28/rpc/jsonrpc/server/http_json_handler.go:140 +0x5d\nnet/http.HandlerFunc.ServeHTTP(0xc005b7c1c0?, {0x340e920?, 0xc0056041c8?}, 0xc0046b9878?)\n\tnet/http/server.go:2084 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0x160?, {0x340e920, 0xc0056041c8}, 0xc003543400)\n\tnet/http/server.go:2462 +0x149\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x33f01c0?, 0xc0010bbf00?}, 0x4143a7?}, {0x340e920?, 0xc0056041c8}, 0xc003543400)\n\tgithub.com/tendermint/tendermint@v0.34.28/rpc/jsonrpc/server/http_server.go:256 +0x122\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x340f2e0?, 0xc000e30460}, 0xc003543400)\n\tgithub.com/tendermint/tendermint@v0.34.28/rpc/jsonrpc/server/http_server.go:229 +0x37f\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x340f2e0?, 0xc000e30460?}, 0x414045?)\n\tnet/http/server.go:2084 +0x2f\nnet/http.serverHandler.ServeHTTP({0x33f7be8?}, {0x340f2e0, 0xc000e30460}, 0xc003543400)\n\tnet/http/server.go:2916 +0x43b\nnet/http.(*conn).serve(0xc003ffe000, {0x3410ca8, 0xc000c7a210})\n\tnet/http/server.go:1966 +0x5d7\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3071 +0x4db\n"
12:18PM DBG rejected bad transaction err=null peerID= res={"check_tx":{"code":111222,"codespace":"undefined","data":null,"events":[],"gas_used":"6666","gas_wanted":"-1","info":"","log":"runtime error: invalid memory address or nil pointer dereference: panic","mempoolError":"","priority":"0","sender":""}} server=node tx="     < \x02\x19 a \"  C 9t     =J5\U00109a84 "
```

**Comment by uptSmart** [comment]
Good Job,Thanks
